### ISSUE TITLE
Denoising

### ISSUE THREAD

**Issue by Vondila** [DassaultSystemes-Technology/dspbr-pt#26]
Your project is fantastic, quite a achievement! I saw another project which is similar to yours, they talk about denoising here in this issue:
hoverinc/ray-tracing-renderer#2
I thought you might have experience in denoising techniques and want to add to the discussion. It would be cool to also see denoising ending up in your project.

**Comment by bsdorra** [comment]
Thanks for the feedback! Denoising is great to reduce time to convergence, unfortunately it also introduces bias which is currently the exact opposite of what we're up to with this renderer.
The project serves as a code sample and visual reference for the Enterprise PBR shading model. Slow convergence is not that much of an issue but introducing error due to filtering unfortunately is.
